name: CI Build & Push (API)

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CargoHub.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/tam-tugek/cargo-hub:latest
            ghcr.io/tam-tugek/cargo-hub:${{ github.sha }}
